name: Build NFO.Editor

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在创建符合格式 v9.0.0 的标签时触发
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为基础环境

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 版本
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 列出当前目录
      run: |
        ls -R  # 列出当前目录结构，帮助调试

    - name: 设置构建名称
      id: set_build_name
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/v.* ]]; then
          BUILD_NAME=${GITHUB_REF#refs/tags/}
        else
          BUILD_NAME=build-$(date +"%Y-%m-%d-%H-%M-%S")
        fi
        echo "BUILD_NAME=${BUILD_NAME}" >> $GITHUB_ENV

    - name: 运行 PyInstaller
      run: |
        pyinstaller --name "${{ env.BUILD_NAME }}" --noconsole --icon="chuizi.ico" --add-data "Img:Img" "NFO.Editor.py"

    - name: 列出 dist 目录
      run: |
        ls -R dist/  # 列出 dist 目录下的文件，帮助确认可执行文件

    - name: 重命名构建产物
      run: |
        ORIGINAL_NAME="dist/${{ env.BUILD_NAME }}"
        NEW_NAME="${{ env.BUILD_NAME }}"
        if [ -f "${ORIGINAL_NAME}" ]; then
          echo "构建产物 ${ORIGINAL_NAME} 存在。"
          mv "${ORIGINAL_NAME}" "${NEW_NAME}"
        else
          echo "错误: 构建产物 ${ORIGINAL_NAME} 不存在。"
          exit 1
        fi

    - name: 打包构建产物
      uses: actions/upload-artifact@v3
      with:
        name: NFO.Editor-build-linux
        path: |
          dist/${{ env.BUILD_NAME }}.*
