name: Build NFO Tools

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1
  PYTHONUTF8: 1
  PYTHONDONTWRITEBYTECODE: 1

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 设置 Python 版本
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.13'
        cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt --no-cache-dir
        pip install pyinstaller==6.3.0

    - name: 设置构建名称
      id: set_build_name
      shell: pwsh
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "push" -and $env:GITHUB_REF -match '^refs/tags/v.*') {
          $BUILD_NAME = $env:GITHUB_REF.Substring(10)
        } else {
          git fetch --tags
          $latestTag = git describe --tags $(git rev-list --tags --max-count=1)
          if ($null -eq $latestTag) {
            Write-Error "未找到任何标签，无法继续。"
            exit 1
          }
          $BUILD_NAME = $latestTag
        }
        echo "build_name=$BUILD_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: 构建所有应用
      shell: pwsh
      run: |
        $apps = @(
          @{
            name = "cg_crop"
            extra_data = "--add-data 'Img;Img'"
          },
          @{
            name = "NFO.Editor.Qt5"
            extra_data = "--add-data 'mapping_actor.xml;.' --add-data 'Img;Img'"
          },
          @{
            name = "cg_rename"
            extra_data = "--add-data 'mapping_actor.xml;.'"
          },
          @{
            name = "cg_dedupe"
            extra_data = ""
          }
        )
        
        foreach ($app in $apps) {
          pyinstaller --name "$($app.name)" `
            --onefile `
            --noconsole `
            --icon="chuizi.ico" `
            --add-data "chuizi.ico;." `
            $($app.extra_data) `
            --runtime-tmpdir "%TEMP%" `
            --clean `
            "$($app.name).py"
        }

    - name: 创建 NSIS 安装脚本
      shell: pwsh
      run: |
        @'
        !include "MUI2.nsh"
        !define PRODUCT_NAME "NFO Tools"
        !define PRODUCT_VERSION "${{ env.build_name }}"
        !define PRODUCT_PUBLISHER "NFO Tools"

        Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
        OutFile "NFOTools.Setup.${{ env.build_name }}.exe"
        InstallDir "$PROGRAMFILES\NFO Tools"
        
        !insertmacro MUI_PAGE_WELCOME
        !insertmacro MUI_PAGE_DIRECTORY
        !insertmacro MUI_PAGE_INSTFILES
        !insertmacro MUI_PAGE_FINISH
        !insertmacro MUI_UNPAGE_CONFIRM
        !insertmacro MUI_UNPAGE_INSTFILES
        
        !insertmacro MUI_LANGUAGE "SimpChinese"
        
        Section "MainSection" SEC01
          SetOutPath "$INSTDIR"
          SetOverwrite ifnewer
          
          File "dist\cg_crop.exe"
          File "dist\NFO.Editor.Qt5.exe"
          File "dist\cg_rename.exe"
          File "dist\cg_dedupe.exe"
          File "chuizi.ico"
          
          CreateDirectory "$SMPROGRAMS\NFO Tools"
          CreateShortCut "$SMPROGRAMS\NFO Tools\NFO Editor.lnk" "$INSTDIR\NFO.Editor.Qt5.exe"
          CreateShortCut "$SMPROGRAMS\NFO Tools\CG Crop.lnk" "$INSTDIR\cg_crop.exe"
          CreateShortCut "$SMPROGRAMS\NFO Tools\CG Rename.lnk" "$INSTDIR\cg_rename.exe"
          CreateShortCut "$SMPROGRAMS\NFO Tools\NFO Dedupe.lnk" "$INSTDIR\cg_dedupe.exe"
          
          WriteUninstaller "$INSTDIR\uninstall.exe"
          
          CreateShortCut "$SMPROGRAMS\NFO Tools\Uninstall.lnk" "$INSTDIR\uninstall.exe"
        SectionEnd
        
        Section "Uninstall"
          Delete "$INSTDIR\uninstall.exe"
          Delete "$INSTDIR\cg_crop.exe"
          Delete "$INSTDIR\NFO.Editor.Qt5.exe"
          Delete "$INSTDIR\cg_rename.exe"
          Delete "$INSTDIR\cg_dedupe.exe"
          Delete "$INSTDIR\chuizi.ico"
          
          Delete "$SMPROGRAMS\NFO Tools\NFO Editor.lnk"
          Delete "$SMPROGRAMS\NFO Tools\CG Crop.lnk"
          Delete "$SMPROGRAMS\NFO Tools\CG Rename.lnk"
          Delete "$SMPROGRAMS\NFO Tools\NFO Dedupe.lnk"
          Delete "$SMPROGRAMS\NFO Tools\Uninstall.lnk"
          
          RMDir "$SMPROGRAMS\NFO Tools"
          RMDir "$INSTDIR"
        SectionEnd
        '@ | Out-File -FilePath "installer.nsi" -Encoding utf8

    - name: 安装 NSIS
      run: |
        choco install nsis -y

    - name: 构建安装程序
      run: |
        makensis installer.nsi

    - name: 上传构建工件
      uses: actions/upload-artifact@v4
      with:
        name: nfo-tools-installer
        path: NFOTools.Setup.${{ env.build_name }}.exe
        retention-days: 7

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 下载安装程序
        uses: actions/download-artifact@v4
        with:
          name: nfo-tools-installer
          path: dist

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.build_name }}
          tag_name: ${{ env.build_name }}
          draft: false
          prerelease: false
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}